---
# tasks file for nginx-k8s-oidc
- name: Get short namespace value
  set_fact:
    oidc_namespace: "{{ oidc_kube_dns | regex_search('(?<=\\.svc\\.)(.*)') }}"

- name: Create nginx-config.yaml
  template:
    src: nginx-config.yaml.j2
    dest: "{{ oidc_files_location }}/nginx-config.yaml"
    backup: "{{ oidc_backup }}"

- name: Create nginx-plus-ingress.yaml
  template:
    src: nginx-plus-ingress.yaml.j2
    dest:  "{{ oidc_files_location }}/nginx-plus-ingress.yaml"
    backup: "{{ oidc_backup }}"

- name: Create openid_connect.js
  template:
    src: openid_connect.js.j2
    dest:  "{{ oidc_files_location }}/openid_connect.js"
    backup: "{{ oidc_backup }}"

- name: Create openid_connect.server_conf
  template:
    src: openid_connect.server_conf.j2
    dest:  "{{ oidc_files_location }}/openid_connect.server_conf"
    backup: "{{ oidc_backup }}"

- name: Create socat.yaml
  template:
    src: socat.yaml.j2
    dest: "{{ oidc_files_location }}/{{ item.value.hostname | regex_replace('\\.', '-') }}-socat.yaml"
    backup: "{{ oidc_backup }}"
  when: item.value.oidc_socat_enable
  loop: "{{ oidc_idps|dict2items }}"

- name: Create headless.yaml
  template:
    src: headless.yaml.j2
    dest:  "{{ oidc_files_location }}/headless.yaml"
    backup: "{{ oidc_backup }}"
  when: oidc_headless
