---
# tasks file for nginx-k8s-oidc

- name: Create nginx-config.yaml
  template:
    src: nginx-config.yaml.j2
    dest: "{{ oidc_files_location }}/nginx-config.yaml"
    backup: "{{ oidc_backup }}"

- name: Insert any http ingress code in nginx-config.yaml
  blockinfile:
    path: "{{ oidc_files_location }}/nginx-config.yaml"
    insertafter: '\$http_user_agent'
    block: |
       map $jwt_claim_preferred_username $jwt_nibr521 {
         default $jwt_claim_preferred_username;
         ~^(?<username>.*)@(?<domain>.*)$ "${username}";
       }
  when: oidc_http_block_file is defined

- name: Create nginx-plus-ingress.yaml
  template:
    src: nginx-plus-ingress.yaml.j2
    dest:  "{{ oidc_files_location }}/nginx-plus-ingress.yaml"
    backup: "{{ oidc_backup }}"

- name: Create openid_connect.js
  template:
    src: openid_connect.js.j2
    dest:  "{{ oidc_files_location }}/openid_connect.js"
    backup: "{{ oidc_backup }}"

- name: Create openid_connect.server_conf
  template:
    src: openid_connect.server_conf.j2
    dest:  "{{ oidc_files_location }}/openid_connect.server_conf"
    backup: "{{ oidc_backup }}"

- name: Create headless.yaml
  template:
    src: headless.yaml.j2
    dest:  "{{ oidc_files_location }}/headless.yaml"
    backup: "{{ oidc_backup }}"
  when: oidc_headless
